### ISSUE TITLE
Segfault in `example.cpp`

### ISSUE THREAD

**Issue by tsunrise** [Trinity-data-store/Trinity#2]
Hi, I tried to run the provided example but got a segfault. Here is the address sanitizer log:
```
ubuntu@ip-172-31-36-119 /p/T/l/build> ./example
=================================================================
==52884==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x602000000150 at pc 0x560942325c75 bp 0x7ffd81e4a990 sp 0x7ffd81e4a980
READ of size 8 at 0x602000000150 thread T0
    #0 0x560942325c74 in bitmap::BitVector::SetValPos(unsigned long, unsigned long, unsigned char) (/proj/Trinity/libmdtrie/build/example+0x26c74)
    #1 0x56094232bd03 in bitmap::CompactVector<unsigned long, (unsigned char)44>::Set(unsigned long, unsigned long) (/proj/Trinity/libmdtrie/build/example+0x2cd03)
    #2 0x560942326f9e in bitmap::CompactPtrVector::Set(unsigned long, void*) (/proj/Trinity/libmdtrie/build/example+0x27f9e)
    #3 0x560942346da2 in tree_block<9ul>::insert_primary_key_at_index(unsigned long, unsigned long, bitmap::CompactPtrVector*) (/proj/Trinity/libmdtrie/build/example+0x47da2)
    #4 0x56094233ce62 in tree_block<9ul>::insert(unsigned long, unsigned long, data_point<9ul>*, unsigned char, unsigned long, unsigned long, unsigned long, bitmap::CompactPtrVector*) (/proj/Trinity/libmdtrie/build/example+0x3de62)
    #5 0x56094233d1fe in tree_block<9ul>::insert(unsigned long, unsigned long, data_point<9ul>*, unsigned char, unsigned long, unsigned long, unsigned long, bitmap::CompactPtrVector*) (/proj/Trinity/libmdtrie/build/example+0x3e1fe)
    #6 0x5609423342dd in tree_block<9ul>::insert_remaining(data_point<9ul>*, unsigned char, unsigned long, bitmap::CompactPtrVector*) (/proj/Trinity/libmdtrie/build/example+0x352dd)
    #7 0x56094232e21a in md_trie<9ul>::insert_trie(data_point<9ul>*, unsigned long) (/proj/Trinity/libmdtrie/build/example+0x2f21a)
    #8 0x560942322dfc in main (/proj/Trinity/libmdtrie/build/example+0x23dfc)
    #9 0x7f37f4088082 in __libc_start_main ../csu/libc-start.c:308
    #10 0x56094231ac1d in _start (/proj/Trinity/libmdtrie/build/example+0x1bc1d)

0x602000000151 is located 0 bytes to the right of 1-byte region [0x602000000150,0x602000000151)
allocated by thread T0 here:
    #0 0x7f37f46da808 in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:144
    #1 0x560942325ab7 in bitmap::BitVector::Init(unsigned long) (/proj/Trinity/libmdtrie/build/example+0x26ab7)
    #2 0x5609423259ef in bitmap::BitVector::BitVector(unsigned long) (/proj/Trinity/libmdtrie/build/example+0x269ef)
    #3 0x56094232bc46 in bitmap::CompactVector<unsigned long, (unsigned char)44>::CompactVector(unsigned long) (/proj/Trinity/libmdtrie/build/example+0x2cc46)
    #4 0x560942326eda in bitmap::CompactPtrVector::CompactPtrVector(unsigned long) (/proj/Trinity/libmdtrie/build/example+0x27eda)
    #5 0x56094232dd71 in md_trie<9ul>::md_trie(unsigned char, unsigned char, unsigned long, std::vector<unsigned char, std::allocator<unsigned char> >, std::vector<unsigned char, std::allocator<unsigned char> >) (/proj/Trinity/libmdtrie/build/example+0x2ed71)
    #6 0x560942322caa in main (/proj/Trinity/libmdtrie/build/example+0x23caa)
    #7 0x7f37f4088082 in __libc_start_main ../csu/libc-start.c:308

SUMMARY: AddressSanitizer: heap-buffer-overflow (/proj/Trinity/libmdtrie/build/example+0x26c74) in bitmap::BitVector::SetValPos(unsigned long, unsigned long, unsigned char)
Shadow bytes around the buggy address:
  0x0c047fff7fd0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c047fff7fe0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c047fff7ff0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x0c047fff8000: fa fa 00 01 fa fa 00 01 fa fa fd fd fa fa fd fd
  0x0c047fff8010: fa fa fd fd fa fa fd fd fa fa 00 01 fa fa 00 01
=>0x0c047fff8020: fa fa fd fa fa fa fd fd fa fa[01]fa fa fa fd fd
  0x0c047fff8030: fa fa fd fd fa fa fd fd fa fa fd fd fa fa fd fd
  0x0c047fff8040: fa fa fd fd fa fa fd fd fa fa fd fd fa fa fd fd
  0x0c047fff8050: fa fa fd fd fa fa fd fd fa fa fd fd fa fa fd fd
  0x0c047fff8060: fa fa fd fd fa fa fd fd fa fa fd fd fa fa 00 01
  0x0c047fff8070: fa fa 00 01 fa fa fd fa fa fa fd fd fa fa fd fd
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
  Shadow gap:              cc
==52884==ABORTING

```

Thanks. 
@MaoZiming

**Comment by MaoZiming** [comment]
Thanks! There was a bug introduced in the most recent PR (https://github.com/Trinity-data-store/Trinity/commit/299bad470b2940286587fb640195545368858d45). I reverted it. The example should run.
I haven't had time to fully clean up the code yet. Plan to do that this week.

**Comment by tsunrise** [comment]
Thanks for your prompt response! I will check soon.

**Comment by tsunrise** [comment]
The example works now. Thanks for the great work and I'm looking forward to see the clean up and updates soon. 👍
